
const app=document.getElementById("app");const money=n=>"KSh "+n.toLocaleString("en-KE");
function show(v){if(v==="home")app.innerHTML=home();if(v==="shop")app.innerHTML=shop();if(v==="orders")app.innerHTML=orders();if(v==="account")app.innerHTML=account();scrollTo(0,0)}
function home(){return `<div class="container"><section class="hero"><div><div class="eyebrow">LOCAL COMMERCE, CONNECTED</div><h1>Find it locally. Buy it confidently.</h1><p>BUSIAN connects customers with local shops, restaurants and service providers, with local prices and delivery.</p><div class="search"><input id="q" placeholder="What are you looking for?"><button class="primary" onclick="search()">Search</button></div><p><button class="primary" onclick="show("shop")">Start shopping</button> <button onclick="roles()">Join BUSIAN</button></p></div><div class="hero-panel"><h2>Your local marketplace.</h2><p>🛍️ Discover local products</p><p>💰 Compare real local prices</p><p>✓ Find verified merchants</p><p>🚴 Get orders delivered</p></div></section><section class="section"><h2>Shop by category</h2><div class="grid">${BUSIAN.categories.map(x=>`<div class="card"><b>${x[1]} ${x[0]}</b></div>`).join("")}</div></section><section class="section"><h2>Popular near you</h2><div class="grid">${BUSIAN.products.map(product).join("")}</div></section><section class="section"><h2>Local businesses on BUSIAN</h2><p class="muted">The public can discover a merchant's shop, products, prices and offers.</p><div class="merchant-grid">${["🏪 Busia Fresh Mart","🍽️ Town Kitchen","📱 Busia Home Electronics"].map(x=>`<div class="card merchant"><div class="avatar">${x[0]}</div><div><b>${x.slice(2)}</b><br><span class="badge">✓ Verified</span></div></div>`).join("")}</div></section></div>`}
function product(x){return `<div class="card product"><div class="image">${x.i}</div><span class="badge">✓ Verified merchant</span><h3>${x.n}</h3><div>${x.m}</div><div class="price">${money(x.p)}</div><button class="primary" onclick="alert("Added to cart — checkout comes next")">Add to cart</button></div>`}
function shop(){return `<div class="container section"><div class="eyebrow">PUBLIC MARKETPLACE</div><h2>Shop local</h2><p>Shop is the public storefront: customers browse merchants, products, services, offers and local prices.</p><div class="search"><input id="q" placeholder="Search products or shops"><button class="primary" onclick="search()">Search</button></div><div class="grid" style="margin-top:18px">${BUSIAN.products.map(product).join("")}</div></div>`}
function search(){let q=(document.getElementById("q")?.value||"").toLowerCase();let a=BUSIAN.products.filter(x=>(x.n+x.m+x.c).toLowerCase().includes(q));app.innerHTML=`<div class="container section"><h2>Search results</h2><div class="grid">${a.map(product).join("")||`<div class="card">No matching products yet.</div>`}</div></div>`}
function orders(){return `<div class="container section"><div class="card guest"><div style="font-size:45px">▣</div><div class="eyebrow">YOUR ORDERS</div><h2>Track your BUSIAN orders</h2><p>Orders belong to a customer account, so payment and delivery status stay in one place.</p><button class="primary" onclick="register("customer")">Create account</button> <button onclick="alert("Login will be connected next")">Log in</button></div></div>`}
function account(){return `<div class="container section"><div class="card guest"><div style="font-size:45px">◯</div><div class="eyebrow">BUSIAN ACCOUNT</div><h2>One account. Multiple approved roles.</h2><p>Start as a customer and add merchant, rider, partner or field-agent roles when needed.</p><button class="primary" onclick="register("customer")">Sign up</button> <button onclick="roles()">Join as business / partner</button></div></div>`}
function roles(){open(`<h2>Join BUSIAN</h2><p>Choose your starting role.</p><div class="roles">${[["customer","🛍️ Customer","Shop and order"],["merchant","🏪 Merchant / Provider","Showcase your business and manage products"],["agent","📍 Field Agent","Digitize local businesses"],["rider","🚴 Rider","Deliver orders"],["partner","🤝 Partner","Refer customers and merchants"]].map(r=>`<button class="role" onclick="register("${r[0]}")"><b>${r[1]}</b><br><small>${r[2]}</small></button>`).join("")}</div>`)}
function register(role){let extra=role==="merchant"?`<label>Business name<input required></label><label>Provider type<select><option>Shop</option><option>Restaurant / Hotel</option><option>Groceries</option><option>Electronics</option><option>Fashion</option><option>Services</option></select></label>`:"";open(`<h2>${role==="customer"?"Create your BUSIAN account":role==="merchant"?"Merchant onboarding":role==="agent"?"Field Agent onboarding":role==="rider"?"Rider onboarding":"Partner onboarding"}</h2><form class="form" onsubmit="event.preventDefault();close();alert("Registration saved — backend verification comes next")"><label>Full name<input required></label><label>Phone number<input required placeholder="07XX XXX XXX"></label>${extra}<button class="primary">Continue</button></form>`)}
function open(h){let d=document.createElement("div");d.className="modal";d.innerHTML=`<div>${h}<p><button onclick="document.getElementById("modal").remove()">Close</button></p></div>`;d.id="modal";document.body.appendChild(d)}
show("home");
