
const app=document.getElementById('app');
function money(n){return 'KSh '+n.toLocaleString('en-KE')}
function show(v){
 if(v==='home')app.innerHTML=home();
 if(v==='shop')app.innerHTML=shop();
 if(v==='orders')app.innerHTML='<div class="container section"><div class="card"><h2>My Orders</h2><p class="muted">Orders will appear here after checkout.</p></div></div>';
}
function home(){return `<div class="container"><section class="hero"><div><small style="color:#0f766e;font-weight:800">LOCAL COMMERCE, CONNECTED</small><h1>Discover what you need. Buy with confidence.</h1><p class="muted">BUSIAN connects customers with local businesses while helping merchants, agents, riders and partners participate in the digital economy.</p><div class="search"><input id="q" placeholder="What are you looking for?"><button class="primary" onclick="search()">Search</button></div><p><button class="primary" onclick="register('customer')">Shop on BUSIAN</button> <button onclick="roleMenu()">Join as a business or partner</button></p></div><div class="panel"><h2>One platform. Multiple opportunities.</h2><p>🛍️ Customers discover local products.</p><p>🏪 Merchants manage stores and prices.</p><p>📍 Field agents digitize local businesses.</p><p>🚴 Riders deliver orders.</p></div></section><section class="section"><h2>Shop by category</h2><div class="grid">${BUSIAN.categories.map(x=>`<div class="card"><b>${x}</b></div>`).join('')}</div></section><section class="section"><h2>Popular local products</h2><div class="grid">${BUSIAN.products.map(product).join('')}</div></section></div>`}
function product(x){return `<div class="card product"><div class="image">${x.i}</div><span class="badge">✓ Verified merchant</span><h3>${x.n}</h3><div class="muted">${x.m}</div><div class="price">${money(x.p)}</div><button class="primary" onclick="alert('Product added to cart — demo')">Add to cart</button></div>`}
function shop(){return `<div class="container section"><h2>BUSIAN Marketplace</h2><div class="search"><input id="q" placeholder="Search products, merchants or categories"><button class="primary" onclick="search()">Search</button></div><div id="products" class="grid" style="margin-top:18px">${BUSIAN.products.map(product).join('')}</div></div>`}
function search(){const q=(document.getElementById('q')?.value||'').toLowerCase();const a=BUSIAN.products.filter(x=>(x.n+x.m+x.c).toLowerCase().includes(q));app.innerHTML=`<div class="container section"><h2>Search results</h2><div class="grid">${a.map(product).join('')||'<div class="card">No matching products yet.</div>'}</div></div>`}
function roleMenu(){open(`<h2>How do you want to join BUSIAN?</h2><div class="roles">${[['merchant','🏪 Merchant / Provider','Manage a digital store, products, prices and orders.'],['agent','📍 Field Agent','Help local businesses register and digitize catalogues.'],['rider','🚴 Rider','Deliver customer orders and manage earnings.'],['partner','🤝 Partner','Refer customers and merchants and track commissions.']].map(r=>`<button class="role" onclick="register('${r[0]}')"><b>${r[1]}</b><br><small>${r[2]}</small></button>`).join('')}</div>`)}
function register(role){let extra='';if(role==='merchant')extra='<label>Business name<input required></label><label>Provider type<select><option>Shop</option><option>Restaurant / Hotel</option><option>Groceries</option><option>Electronics</option><option>Fashion</option><option>Services</option></select></label>';if(role==='rider')extra='<label>Transport type<select><option>Motorcycle</option><option>Bicycle</option><option>Car</option></select></label>';if(role==='agent')extra='<label>Preferred territory<input placeholder="Town / area"></label>';open(`<h2>${role==='merchant'?'Merchant onboarding':role==='agent'?'Field Agent onboarding':role==='rider'?'Rider onboarding':'Partner onboarding'}</h2><form class="form" onsubmit="saveRole(event,'${role}')"><label>Full name<input required></label><label>Phone number<input required placeholder="07XX XXX XXX"></label>${extra}<div class="card"><small>This prototype uses the lifecycle: Register → Verify → Activate → Operate → Update. Live verification will be connected to the backend.</small></div><button class="primary">Continue</button></form>`)}
function saveRole(e,role){e.preventDefault();close();dashboard(role)}
function dashboard(role){const titles={merchant:'Merchant Portal',agent:'Field Agent Workspace',rider:'Rider Workspace',partner:'Partner Workspace'};const bodies={merchant:`<h3>Product & price management</h3><p class="muted">Add products, update local prices, manage availability and orders.</p><button class="primary" onclick="addProduct()">+ Add product</button><p class="card">Product lifecycle: Draft → Submitted → Approved → Live → Updated / Unavailable → Archived.</p>`,agent:`<h3>Merchant field work</h3><p class="muted">Find businesses, verify information, capture products and follow up.</p><button class="primary">+ Onboard merchant</button>`,rider:`<h3>Delivery lifecycle</h3><p>Go online → Accept → Pick up → Deliver → Confirm → Earnings.</p>`,partner:`<h3>Commission lifecycle</h3><p>Referral → Attribution → Qualifying activity → Pending → Approved → Paid.</p>`};app.innerHTML=`<div class="container section"><small style="color:#0f766e;font-weight:800">${role.toUpperCase()}</small><h2>${titles[role]}</h2><div class="stats"><div class="stat">Activity<b>0</b></div><div class="stat">Pending<b>0</b></div><div class="stat">Completed<b>0</b></div><div class="stat">Earnings<b>KSh 0</b></div></div><div class="card">${bodies[role]}</div></div>`}
function addProduct(){open(`<h2>Add product</h2><form class="form" onsubmit="event.preventDefault();close();alert('Product saved as draft — demo')"><label>Product name<input required placeholder="e.g. Samsung 55 inch Smart TV"></label><label>Category<select><option>Electronics</option><option>Food</option><option>Groceries</option><option>Fashion</option><option>Beauty</option><option>Services</option></select></label><label>Price (KSh)<input type="number" required></label><label>Availability<select><option>Available</option><option>Unavailable</option></select></label><label>Image<input type="file" accept="image/*"></label><button class="primary">Save draft</button></form>`)}
function open(html){const d=document.createElement('div');d.className='modal';d.innerHTML=`<div>${html}<p><button onclick="close()">Close</button></p></div>`;d.id='modal';document.body.appendChild(d)}
function close(){document.getElementById('modal')?.remove()}
show('home');
